[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "27423eab93bcab3dd95dea65e5bf37aeffa9865b"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "4f03165114d994fbeae31829cae397f05c4e0da5e88d25a7bc4885386d84762b"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.15+0/iceberg_rust_ffi.v0.7.15.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "12579a56548af6e15efb6472cf38447fd2cfc436"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "75075767a523de47785416d763ebcdbe1cfbf6e018af76688f1f49f7f69903ac"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.15+0/iceberg_rust_ffi.v0.7.15.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "d76daf200eb280d07f13e2d1d17552644da1c4f3"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "009f09941a250e472d446e107c00389c874f87a782c9f7e37e5664fc7f6a755c"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.15+0/iceberg_rust_ffi.v0.7.15.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "a664cacaf788d39970936405620886c20c7598d7"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "a2f071ed0920ccc3f566c1aac5465013fad9a78afe57fe8357f8c906557e53ec"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.15+0/iceberg_rust_ffi.v0.7.15.x86_64-linux-gnu.tar.gz"
