[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "867d37f1adc3fa8ac804fd22c2c705f21cce2224"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "bc40eb58a26e3f932ba9ca079238c01c1b16bfa6361892f76e00d22dc81a96c1"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.17+0/iceberg_rust_ffi.v0.7.17.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "4e80740b63f0f42cfbced5727978466c971aeec8"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "3838dd83e1919d6e5045e7d06589e842201cbc9cae2e452dec76f7c5b7f552a5"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.17+0/iceberg_rust_ffi.v0.7.17.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "2604124cda301bf657727aef8e7f87ed27bb8c1d"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "d33293b2ba58957cd3e57c59bb72f05eabd0f27772e8adf3dd563538032fc9bb"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.17+0/iceberg_rust_ffi.v0.7.17.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "671ad16929e9d6f8c49c4f6b313760def1d0d141"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "6732aacdd7e84d6f77e9ee3338818f5823dee4db3d9b1335df5acf7fb699cfcb"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.17+0/iceberg_rust_ffi.v0.7.17.x86_64-linux-gnu.tar.gz"
