[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "6f3ddd17149ab45c6a5c86510016e40d5eafd07b"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "54cce682beb1fe281dd1430dd0b14647070be13f41111ea9e65e1b0aaf2ea87e"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.20+0/iceberg_rust_ffi.v0.7.20.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "405d6d6e3b9b921f2d4f26ac3abc10dd9d116386"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "df9de6f78e5f8d5e607c2d4bbf8f77b7bddbd58ac9507255730321b92dd9b375"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.20+0/iceberg_rust_ffi.v0.7.20.aarch64-linux-gnu.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "38f55ec3cad0eea9e7180e661e79f9f2ec402aeb"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "c91b4120b1dab90b2773774762c959c2f141fdbb37ef3fa4bcc02461256dc191"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.20+0/iceberg_rust_ffi.v0.7.20.x86_64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "a6032c9622055439907d17b658c33217caf4b3a3"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "6b7eaa520290fb5801b7452268b20e93e4fac069eb8f5a87375d88fe43be58e3"
    url = "https://github.com/JuliaBinaryWrappers/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.7.20+0/iceberg_rust_ffi.v0.7.20.x86_64-linux-gnu.tar.gz"
